print('Please enter the number of lives.')
Lives = input()
print('Please enter the energy level.')
Energy = input()
print('Please enter the shield level.')
Shield = input()
print('\n Health has been set:')
print('Lives  ->' + str(Lives)) 
print('Energy ->' + str(Energy))
print('Shield ->' + str(Shield))
